### ISSUE TITLE
ArcheRage 3+ Could it work?

### ISSUE THREAD

**Issue by Kalle801** [Yanlong-LI/Archeage-Server-emulator-or-files#1]
Hello i try to run your emulator with ArcheRage 3+ but im only able to see the ServerList and can't login.
As you already told in the Readme file its not supported yet but will you continue to work on it?

Best Regards from Germany ;)

PS: Does it already work with 2.9 (ArcheRage) if so, i need to find the older client.

**Comment by yanlong-li** [comment]
Sorry, I can't help you. He is not available.

**Comment by Kalle801** [comment]
But did it work with version 2.9 ?

**Comment by yanlong-li** [comment]
No

**Comment by Kalle801** [comment]
Would be great if you can fix it anytime ;)

**Comment by Rain0Ash** [comment]
I saw the code. There's only a launcher, after trying to login the code ends. And to finish it - you need to decrypt the packages, what is almost impossible, as I understand.

**Comment by Kalle801** [comment]
you are logged in with the correct cmd line and can chose a server. but after clicking the server it DC's you.

**Comment by Rain0Ash** [comment]
Yes, I meant this. Already forgot what was there, a couple of months have passed. But the essence has not changed - for next step need decrypt packages.

**Comment by NL0bP** [comment]
See my repository https://github.com/NL0bP/Archeage-Server-emulator where the logon packages for the lobby are parsed.

**Comment by Kalle801** [comment]
That mean, with ur files it could work? @NL0bP

**Comment by Kalle801** [comment]
I can not compile the login server of ur repositiy. 

Many errors like this:

Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile	Unterdrückungszustand
Fehler	CS0246	Der Typ- oder Namespacename "MySql" wurde nicht gefunden (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).	ArcheAge Login Server	C:\Users\Kalle\Downloads\Archeage-Server-emulator-master\Archeage-Server-emulator-master\ArcheAgeLogin\ArcheAge\Holders\AccountHolder.cs	2	Aktiv

**Comment by NL0bP** [comment]
With my files you can go to the lobby.

**Comment by Kalle801** [comment]
Yes it work till the lobby. Character creation and / or joining the world, does not work till now it seems.

Great work so far :)

**Comment by NL0bP** [comment]
Server packets are decrypted. Could not decrypt client packages

**Comment by yanlong-li** [comment]
Oh, I am not sure. This seems to have a new progress. I will look at it later.
